---
- name: install libselinux-python
  yum:
    name: libselinux-python
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare('7.0', '<')

- import_tasks: pgdg10.yml

- import_role: 
    name: geerlingguy.postgresql
  vars:
    postgresql_databases:
    - name: '{{ postgres_db_name }}'
    postgresql_users:
    - name: '{{ postgres_db_user }}'
      password: '{{ postgres_db_user_password }}'
    postgresql_enablerepo: pgdg10
    postgresql_version: 10
    postgresql_data_dir: /var/lib/pgsql/10/data
    postgresql_bin_path: /usr/pgsql-10/bin
    postgresql_config_path: /var/lib/pgsql/10/data
    postgresql_daemon: postgresql-10
    postgresql_packages:
    - postgresql10
    - postgresql10-server
    - postgresql10-libs
    - postgresql10-contrib
    - postgresql10-devel