---
- name: install pgdg-redhat-repo-latest PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-6-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare('7.0', '<')

- name: install pgdg-redhat-repo-latest PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare('7.0', '>=') and ansible_distribution_version is version_compare('8.0', '<')

- name: install pgdg-redhat-repo-latest PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare('8.0', '>=')  